title: Craig Akutagawa
description: ようこそ　クレゴの世界へ
description_lang: ja
url: https://craig-akutagawa.github.io
lang: en-US
avatar_url: "https://avatars.githubusercontent.com/u/200924220?s=400&u=b3885895e64a7b94b007e42ef446a49b895ede6e&v=4"
theme: jekyll-theme-cayman
show_downloads: false
permalink: pretty
markdown: kramdown
exclude:
  - tools
  - tmp
  - .jekyll-cache
  - _site
